# Generated by Django 4.0.5 on 2022-06-07 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('body', models.TextField(blank=True, null=True)),
                ('poster_image_lg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='images/Poster')),
                ('poster_image_md', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('poster_image_sm', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('posted_on', models.DateTimeField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=45, null=True)),
                ('post_type', models.CharField(blank=True, max_length=34, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='manhua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categoryimage', models.ImageField(blank=True, null=True, upload_to='images/category')),
                ('author', models.CharField(blank=True, max_length=225, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('story', models.TextField()),
                ('chapters', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=23, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='manhwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('categoryimage', models.ImageField(blank=True, null=True, upload_to='images/category')),
                ('author', models.CharField(blank=True, max_length=225, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('story', models.TextField()),
                ('chapters', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=23, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=234)),
                ('comment', models.TextField()),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.allpost')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='allpost',
            name='manhua',
            field=models.ManyToManyField(blank=True, to='blog.manhua'),
        ),
        migrations.AddField(
            model_name='allpost',
            name='manhwa',
            field=models.ManyToManyField(blank=True, to='blog.manhwa'),
        ),
    ]
